import type { Metadata } from 'next'
import Alert from './alert'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="w-[100vw] h-[100vh] flex flex-col">
        <Header></Header>
        <Alert>
          {children}
        </Alert>
      </body>
    </html>
  )
}

function Header() {
  return (
    <header className="w-full h-[32px] bg-sky-500 flex justify-center items-center gap-x-[10px]">
      <a href="/account">账户</a>
      <a href="/">某航空</a>
    </header>
  )
}
